apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer   # agar cluster ke bahar expose karna ho to "NodePort" ya "LoadBalancer" use karna
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
