on:
  push:
    branches:
    - main
jobs:
  test:
    name: My First Github Action Yaml
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
      - name: Terraform Init
        uses: terraform init
  
      - name: Terraform Validate
        uses: terraform validate
    
      - name: Terraform plan
        uses: terraform plan -input=false
  
      - name: Terraform Apply
        uses: terraform apply --auto-approve -input=false
    


